// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
/**
 * Block quotation with size, weight, and color.
 *
 * Radix Themes component — re-exported from `@radix-ui/themes`.
 */
export { Blockquote, type BlockquoteProps } from '@radix-ui/themes';
