// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
import { Blockquote, Flex } from '@monorepo-boilerplate/ui';
import type { Meta, StoryObj } from '@storybook/react-vite';

const meta = {
  title: 'Typography/Blockquote',
  component: Blockquote,
  args: { children: 'Design is not just what it looks like — it is how it works.' },
  argTypes: {
    size: { control: { type: 'select' }, options: ['2', '3', '4', '5'] },
  },
  render: (args) => <Blockquote {...args} />,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof Blockquote>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};

export const Size: Story = {
  render: () => (
    <Flex gap="3" align="center" wrap="wrap">
      {(['2', '3', '4', '5'] as const).map((value) => (
        <Blockquote key={value} size={value}>
          Design is not just what it looks like — it is how it works.
        </Blockquote>
      ))}
    </Flex>
  ),
};
