// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
/**
 * Inline code with variant (solid/soft/outline/ghost), size, and color.
 *
 * Radix Themes component — re-exported from `@radix-ui/themes`.
 */
export { Code, type CodeProps } from "@radix-ui/themes";
