// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
import { Code, Flex } from '@monorepo-boilerplate/ui';
import type { Meta, StoryObj } from '@storybook/react-vite';

const meta = {
  title: 'Typography/Code',
  component: Code,
  args: { children: 'const x = 1' },
  argTypes: {
    variant: { control: { type: 'select' }, options: ['solid', 'soft', 'outline', 'ghost'] },
    size: { control: { type: 'select' }, options: ['1', '2', '3'] },
  },
  render: (args) => <Code {...args} />,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof Code>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};

export const Variant: Story = {
  render: () => (
    <Flex gap="3" align="center" wrap="wrap">
      {(['solid', 'soft', 'outline', 'ghost'] as const).map((value) => (
        <Code key={value} variant={value}>
          const x = 1
        </Code>
      ))}
    </Flex>
  ),
};

export const Size: Story = {
  render: () => (
    <Flex gap="3" align="center" wrap="wrap">
      {(['1', '2', '3'] as const).map((value) => (
        <Code key={value} size={value}>
          const x = 1
        </Code>
      ))}
    </Flex>
  ),
};
