// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
import { Em } from '@monorepo-boilerplate/ui';
import type { Meta, StoryObj } from '@storybook/react-vite';

const meta = {
  title: 'Typography/Em',
  component: Em,
  args: { children: 'emphasized' },
  render: (args) => <Em {...args} />,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof Em>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
