// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
/**
 * Emphasized (italic) inline text. Renders an <em>.
 *
 * Radix Themes component — re-exported from `@radix-ui/themes`.
 */
export { Em, type EmProps } from "@radix-ui/themes";
