// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
/**
 * Section heading with size (1–9) and weight. Renders an <h1>–<h6>.
 *
 * Radix Themes component — re-exported from `@radix-ui/themes`.
 */
export { Heading, type HeadingProps } from "@radix-ui/themes";
