// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
import { Heading, Flex } from '@monorepo-boilerplate/ui';
import type { Meta, StoryObj } from '@storybook/react-vite';

const meta = {
  title: 'Typography/Heading',
  component: Heading,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof Heading>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {
  render: () => <Heading>Heading</Heading>,
};

export const Size: Story = {
  render: () => (
    <Flex gap="3" align="center" wrap="wrap">
      {(['3', '4', '5', '6', '7', '8'] as const).map((value) => (
        <Heading key={value} size={value}>
          Heading
        </Heading>
      ))}
    </Flex>
  ),
};
