// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
/**
 * Keyboard input hint. Renders a <kbd>.
 *
 * Radix Themes component — re-exported from `@radix-ui/themes`.
 */
export { Kbd, type KbdProps } from "@radix-ui/themes";
