// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
import { Kbd, Flex } from "@radix-ui/themes";
import type { Meta, StoryObj } from "@storybook/react-vite";

const meta = {
  title: "Typography/Kbd",
  component: Kbd,
  parameters: { layout: "padded" },
} satisfies Meta<typeof Kbd>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {
  render: () => <Kbd>⌘K</Kbd>,
};

export const Size: Story = {
  render: () => (
    <Flex gap="3" align="center" wrap="wrap">
      {(["1", "3", "5"] as const).map((value) => (
        <Kbd key={value} size={value}>
          ⌘K
        </Kbd>
      ))}
    </Flex>
  ),
};
