// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
import { Link, Flex } from "@monorepo-boilerplate/ui";
import type { Meta, StoryObj } from "@storybook/react-vite";

const meta = {
  title: "Typography/Link",
  component: Link,
  parameters: { layout: "padded" },
} satisfies Meta<typeof Link>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {
  render: () => <Link>Link</Link>,
};

export const Underline: Story = {
  render: () => (
    <Flex gap="3" align="center" wrap="wrap">
      {(["auto", "always", "hover", "none"] as const).map((value) => (
        <Link key={value} underline={value}>
          Link
        </Link>
      ))}
    </Flex>
  ),
};

export const Size: Story = {
  render: () => (
    <Flex gap="3" align="center" wrap="wrap">
      {(["2", "3", "4"] as const).map((value) => (
        <Link key={value} size={value}>
          Link
        </Link>
      ))}
    </Flex>
  ),
};
