// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
/**
 * Styled anchor with underline behavior, size, weight, and color. Use asChild for routing links.
 *
 * Radix Themes component — re-exported from `@radix-ui/themes`.
 */
export { Link, type LinkProps } from "@radix-ui/themes";
