// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
/**
 * Short inline quotation. Renders a <q>.
 *
 * Radix Themes component — re-exported from `@radix-ui/themes`.
 */
export { Quote, type QuoteProps } from '@radix-ui/themes';
