// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
/**
 * Bold inline text. Renders a <strong>.
 *
 * Radix Themes component — re-exported from `@radix-ui/themes`.
 */
export { Strong, type StrongProps } from '@radix-ui/themes';
