// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
/**
 * Body text with size (1–9), weight, and color. Renders span/div/label/p.
 *
 * Radix Themes component — re-exported from `@radix-ui/themes`.
 */
export { Text, type TextProps } from '@radix-ui/themes';
