// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
import { Text, Flex } from "@monorepo-boilerplate/ui";
import type { Meta, StoryObj } from "@storybook/react-vite";

const meta = {
  title: "Typography/Text",
  component: Text,
  parameters: { layout: "padded" },
} satisfies Meta<typeof Text>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {
  render: () => <Text>The quick brown fox jumps over the lazy dog.</Text>,
};

export const Size: Story = {
  render: () => (
    <Flex gap="3" align="center" wrap="wrap">
      {(["1", "2", "3", "4", "5", "6"] as const).map((value) => (
        <Text key={value} size={value}>
          The quick brown fox jumps over the lazy dog.
        </Text>
      ))}
    </Flex>
  ),
};

export const Weight: Story = {
  render: () => (
    <Flex gap="3" align="center" wrap="wrap">
      {(["light", "regular", "medium", "bold"] as const).map((value) => (
        <Text key={value} weight={value}>
          The quick brown fox jumps over the lazy dog.
        </Text>
      ))}
    </Flex>
  ),
};
