// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
/**
 * Confirmation dialog that interrupts. Compose AlertDialog.Root/Trigger/Content/Action/Cancel.
 *
 * Radix Themes component — re-exported from `@radix-ui/themes`. Compound parts: Root, Trigger, Content, Title, Description, Action, Cancel.
 */
export { AlertDialog } from "@radix-ui/themes";
