// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
/**
 * Modal dialog. Compose Dialog.Root/Trigger/Content/Title/Description/Close.
 *
 * Radix Themes component — re-exported from `@radix-ui/themes`. Compound parts: Root, Trigger, Content, Title, Description, Close.
 */
export { Dialog } from "@radix-ui/themes";
