// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
/**
 * Preview card shown on hover. Compose HoverCard.Root/Trigger/Content.
 *
 * Radix Themes component — re-exported from `@radix-ui/themes`. Compound parts: Root, Trigger, Content.
 */
export { HoverCard } from '@radix-ui/themes';
