// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
/**
 * Floating panel anchored to a trigger. Compose Popover.Root/Trigger/Content.
 *
 * Radix Themes component — re-exported from `@radix-ui/themes`. Compound parts: Root, Trigger, Content, Close, Anchor.
 */
export { Popover } from "@radix-ui/themes";
