// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
/**
 * Short hover/focus hint. Wraps a child and takes a `content` prop.
 *
 * Radix Themes component — re-exported from `@radix-ui/themes`.
 */
export { Tooltip, type TooltipProps } from '@radix-ui/themes';
