// Code generated by @monorepo-boilerplate/catalog-extractor. DO NOT EDIT.
// Run `pnpm catalog:generate` to refresh after changing a component or its *.catalog.ts.

import type { ComponentMeta } from "./catalog-schema";

export const componentRegistry: readonly ComponentMeta[] = [
  {
    name: "Badge",
    description: "Small status/label pill with variants. Renders a <span>.",
    importPath: "@monorepo-boilerplate/ui",
    sourcePath: "src/components/badge.tsx",
    tier: "Primitive",
    renderEnvironment: "server",
    props: [
      {
        name: "variant",
        type: '"default" | "outline" | "muted"',
        required: false,
      },
      {
        name: "...span",
        type: 'ComponentPropsWithRef<"span">',
        required: false,
      },
    ],
    variants: [
      {
        name: "variant",
        values: ["default", "outline", "muted"],
        default: "default",
      },
    ],
    examples: [
      {
        label: "default",
        code: "<Badge>New</Badge>",
      },
      {
        label: "muted",
        code: '<Badge variant="muted">Beta</Badge>',
      },
    ],
    intent: {
      use: ["Compact status or category labels inline with text or in lists."],
      avoid: ["Interactive actions — a Badge is non-interactive; use a Button."],
    },
  },
  {
    name: "Button",
    description: "Clickable button with style and size variants.",
    importPath: "@monorepo-boilerplate/ui",
    sourcePath: "src/components/button.tsx",
    tier: "Primitive",
    renderEnvironment: "server",
    props: [
      {
        name: "variant",
        type: '"primary" | "outline" | "ghost" | "destructive"',
        required: false,
      },
      {
        name: "size",
        type: '"sm" | "md" | "lg"',
        required: false,
      },
      {
        name: "...button",
        type: 'ComponentPropsWithRef<"button">',
        required: false,
      },
    ],
    variants: [
      {
        name: "variant",
        values: ["primary", "outline", "ghost", "destructive"],
        default: "primary",
      },
      {
        name: "size",
        values: ["sm", "md", "lg"],
        default: "md",
      },
    ],
    examples: [
      {
        label: "primary",
        code: "<Button>Save</Button>",
      },
      {
        label: "outline large",
        code: '<Button variant="outline" size="lg">Cancel</Button>',
      },
      {
        label: "destructive",
        code: '<Button variant="destructive">Delete</Button>',
      },
    ],
    intent: {
      use: [
        "Triggering an action where the click is the primary event (submit, delete, run a handler).",
        "Adopting button styling on another element via buttonVariants().",
      ],
      avoid: [
        "Navigating to a URL — use a Next <Link> (optionally with buttonVariants()).",
        "Toggling a visible on/off state — use a Switch or Checkbox.",
      ],
    },
  },
  {
    name: "Card",
    description: "Bordered surface container for grouping related content.",
    importPath: "@monorepo-boilerplate/ui",
    sourcePath: "src/components/card.tsx",
    tier: "Primitive",
    renderEnvironment: "server",
    props: [
      {
        name: "...div",
        type: 'ComponentPropsWithRef<"div">',
        required: false,
      },
    ],
    examples: [
      {
        label: "default",
        code: "<Card>Content</Card>",
      },
    ],
    intent: {
      use: ["Grouping related content on an elevated surface (bg-surface)."],
      avoid: ["Page-level layout — compose blocks/templates instead of nesting many Cards."],
    },
  },
  {
    name: "Dialog",
    description: "Modal dialog (Radix) with overlay, focus trap, and keyboard handling.",
    importPath: "@monorepo-boilerplate/ui",
    sourcePath: "src/components/dialog.tsx",
    tier: "Primitive",
    renderEnvironment: "client",
    props: [
      {
        name: "Dialog",
        type: "Radix Dialog.Root props (open, onOpenChange, …)",
        required: false,
      },
      {
        name: "DialogContent",
        type: "ComponentPropsWithRef<typeof Dialog.Content>",
        required: false,
      },
    ],
    examples: [
      {
        label: "basic",
        code: "<Dialog>\n  <DialogTrigger>Open</DialogTrigger>\n  <DialogContent>\n    <DialogTitle>Title</DialogTitle>\n    <DialogDescription>Body</DialogDescription>\n  </DialogContent>\n</Dialog>",
      },
    ],
    intent: {
      use: ["Blocking, focus-trapped interactions: confirmations, forms, detail overlays."],
      avoid: ["Non-blocking transient hints — use Tooltip. Always render DialogTitle for a11y."],
    },
  },
  {
    name: "Input",
    description: "Text input styled with the kit's semantic tokens.",
    importPath: "@monorepo-boilerplate/ui",
    sourcePath: "src/components/input.tsx",
    tier: "Primitive",
    renderEnvironment: "server",
    props: [
      {
        name: "...input",
        type: 'ComponentPropsWithRef<"input">',
        required: false,
      },
    ],
    examples: [
      {
        label: "labelled email",
        code: '<label htmlFor="email">Email<Input id="email" type="email" /></label>',
      },
    ],
    intent: {
      use: ["Single-line text entry, always paired with a <label htmlFor> or aria-label."],
      avoid: ["Relying on placeholder as the accessible name — it is not a label."],
    },
  },
  {
    name: "Select",
    description: "Accessible single-select dropdown (Radix) styled with kit tokens.",
    importPath: "@monorepo-boilerplate/ui",
    sourcePath: "src/components/select.tsx",
    tier: "Primitive",
    renderEnvironment: "client",
    props: [
      {
        name: "Select",
        type: "Radix Select.Root props (value, onValueChange, …)",
        required: false,
      },
      {
        name: "SelectTrigger",
        type: "ComponentPropsWithRef<typeof Select.Trigger>",
        required: false,
      },
    ],
    examples: [
      {
        label: "basic",
        code: '<Select>\n  <SelectTrigger><SelectValue placeholder="Pick one" /></SelectTrigger>\n  <SelectContent>\n    <SelectItem value="a">A</SelectItem>\n    <SelectItem value="b">B</SelectItem>\n  </SelectContent>\n</Select>',
      },
    ],
    intent: {
      use: ["Choosing one option from a small-to-medium list with full keyboard a11y."],
      avoid: [
        "Free text entry — use Input. Multi-select — compose checkboxes or a dedicated control.",
      ],
    },
  },
  {
    name: "Tooltip",
    description: "Hover/focus tooltip (Radix). Requires a TooltipProvider ancestor.",
    importPath: "@monorepo-boilerplate/ui",
    sourcePath: "src/components/tooltip.tsx",
    tier: "Primitive",
    renderEnvironment: "client",
    props: [
      {
        name: "TooltipContent",
        type: "ComponentPropsWithRef<typeof Tooltip.Content>",
        required: false,
      },
    ],
    examples: [
      {
        label: "basic",
        code: "<TooltipProvider>\n  <Tooltip>\n    <TooltipTrigger>Hover</TooltipTrigger>\n    <TooltipContent>Hint</TooltipContent>\n  </Tooltip>\n</TooltipProvider>",
      },
    ],
    intent: {
      use: ["Short, transient hints on hover/focus for an already-labelled control."],
      avoid: ["Essential information (tooltips are not reliably reachable on touch)."],
    },
  },
];
