// Code generated by @monorepo-boilerplate/catalog-extractor. DO NOT EDIT.
// Run `pnpm catalog:generate` to refresh after changing a component or its *.catalog.ts.

import type { ComponentMeta } from "./catalog-schema";

export const componentRegistry: readonly ComponentMeta[] = [
  {
    name: "Badge",
    description: "Small status/label pill with variants. Renders a <span>.",
    importPath: "@monorepo-boilerplate/ui",
    sourcePath: "src/components/badge.tsx",
    examplePath: "examples/badge.example.tsx",
    tier: "Primitive",
    renderEnvironment: "server",
    props: [
      {
        name: "variant",
        type: '"default" | "outline" | "muted"',
        required: false,
      },
      {
        name: "...span",
        type: 'ComponentPropsWithRef<"span">',
        required: false,
      },
    ],
    variants: [
      {
        name: "variant",
        values: ["default", "outline", "muted"],
        default: "default",
      },
    ],
    examples: [
      {
        label: "default",
        code: "<Badge>New</Badge>",
      },
      {
        label: "muted",
        code: '<Badge variant="muted">Beta</Badge>',
      },
    ],
    intent: {
      use: ["Compact status or category labels inline with text or in lists."],
      avoid: ["Interactive actions — a Badge is non-interactive; use a Button."],
    },
  },
  {
    name: "Button",
    description: "Clickable button with style and size variants.",
    importPath: "@monorepo-boilerplate/ui",
    sourcePath: "src/components/button.tsx",
    examplePath: "examples/button.example.tsx",
    tier: "Primitive",
    renderEnvironment: "server",
    props: [
      {
        name: "variant",
        type: '"primary" | "outline" | "ghost" | "destructive"',
        required: false,
      },
      {
        name: "size",
        type: '"sm" | "md" | "lg"',
        required: false,
      },
      {
        name: "...button",
        type: 'ComponentPropsWithRef<"button">',
        required: false,
      },
    ],
    variants: [
      {
        name: "variant",
        values: ["primary", "outline", "ghost", "destructive"],
        default: "primary",
      },
      {
        name: "size",
        values: ["sm", "md", "lg"],
        default: "md",
      },
    ],
    examples: [
      {
        label: "primary",
        code: "<Button>Save</Button>",
      },
      {
        label: "outline large",
        code: '<Button variant="outline" size="lg">Cancel</Button>',
      },
      {
        label: "destructive",
        code: '<Button variant="destructive">Delete</Button>',
      },
    ],
    intent: {
      use: [
        "Triggering an action where the click is the primary event (submit, delete, run a handler).",
        "Adopting button styling on another element via buttonVariants().",
      ],
      avoid: [
        "Navigating to a URL — use a Next <Link> (optionally with buttonVariants()).",
        "Toggling a visible on/off state — use a Switch or Checkbox.",
      ],
    },
  },
  {
    name: "Card",
    description: "Bordered surface container for grouping related content.",
    importPath: "@monorepo-boilerplate/ui",
    sourcePath: "src/components/card.tsx",
    examplePath: "examples/card.example.tsx",
    tier: "Primitive",
    renderEnvironment: "server",
    props: [
      {
        name: "...div",
        type: 'ComponentPropsWithRef<"div">',
        required: false,
      },
    ],
    examples: [
      {
        label: "default",
        code: "<Card>Content</Card>",
      },
    ],
    intent: {
      use: ["Grouping related content on an elevated surface (bg-surface)."],
      avoid: ["Page-level layout — compose blocks/templates instead of nesting many Cards."],
    },
  },
  {
    name: "Dialog",
    description: "Modal dialog (Radix) with overlay, focus trap, and keyboard handling.",
    importPath: "@monorepo-boilerplate/ui",
    sourcePath: "src/components/dialog.tsx",
    examplePath: "examples/dialog.example.tsx",
    tier: "Primitive",
    renderEnvironment: "client",
    props: [
      {
        name: "Dialog",
        type: "Radix Dialog.Root props (open, onOpenChange, …)",
        required: false,
      },
      {
        name: "DialogContent",
        type: "ComponentPropsWithRef<typeof Dialog.Content>",
        required: false,
      },
    ],
    examples: [
      {
        label: "basic",
        code: "<Dialog>\n  <DialogTrigger>Open</DialogTrigger>\n  <DialogContent>\n    <DialogTitle>Title</DialogTitle>\n    <DialogDescription>Body</DialogDescription>\n  </DialogContent>\n</Dialog>",
      },
    ],
    intent: {
      use: ["Blocking, focus-trapped interactions: confirmations, forms, detail overlays."],
      avoid: ["Non-blocking transient hints — use Tooltip. Always render DialogTitle for a11y."],
    },
  },
  {
    name: "Input",
    description: "Text input styled with the kit's semantic tokens.",
    importPath: "@monorepo-boilerplate/ui",
    sourcePath: "src/components/input.tsx",
    examplePath: "examples/input.example.tsx",
    tier: "Primitive",
    renderEnvironment: "server",
    props: [
      {
        name: "...input",
        type: 'ComponentPropsWithRef<"input">',
        required: false,
      },
    ],
    examples: [
      {
        label: "labelled email",
        code: '<label htmlFor="email">Email<Input id="email" type="email" /></label>',
      },
    ],
    intent: {
      use: ["Single-line text entry, always paired with a <label htmlFor> or aria-label."],
      avoid: ["Relying on placeholder as the accessible name — it is not a label."],
    },
  },
  {
    name: "Select",
    description: "Accessible single-select dropdown (Radix) styled with kit tokens.",
    importPath: "@monorepo-boilerplate/ui",
    sourcePath: "src/components/select.tsx",
    examplePath: "examples/select.example.tsx",
    tier: "Primitive",
    renderEnvironment: "client",
    props: [
      {
        name: "Select",
        type: "Radix Select.Root props (value, onValueChange, …)",
        required: false,
      },
      {
        name: "SelectTrigger",
        type: "ComponentPropsWithRef<typeof Select.Trigger>",
        required: false,
      },
    ],
    examples: [
      {
        label: "basic",
        code: '<Select>\n  <SelectTrigger><SelectValue placeholder="Pick one" /></SelectTrigger>\n  <SelectContent>\n    <SelectItem value="a">A</SelectItem>\n    <SelectItem value="b">B</SelectItem>\n  </SelectContent>\n</Select>',
      },
    ],
    intent: {
      use: ["Choosing one option from a small-to-medium list with full keyboard a11y."],
      avoid: [
        "Free text entry — use Input. Multi-select — compose checkboxes or a dedicated control.",
      ],
    },
  },
  {
    name: "Tooltip",
    description: "Hover/focus tooltip (Radix). Requires a TooltipProvider ancestor.",
    importPath: "@monorepo-boilerplate/ui",
    sourcePath: "src/components/tooltip.tsx",
    examplePath: "examples/tooltip.example.tsx",
    tier: "Primitive",
    renderEnvironment: "client",
    props: [
      {
        name: "TooltipContent",
        type: "ComponentPropsWithRef<typeof Tooltip.Content>",
        required: false,
      },
    ],
    examples: [
      {
        label: "basic",
        code: "<TooltipProvider>\n  <Tooltip>\n    <TooltipTrigger>Hover</TooltipTrigger>\n    <TooltipContent>Hint</TooltipContent>\n  </Tooltip>\n</TooltipProvider>",
      },
    ],
    intent: {
      use: ["Short, transient hints on hover/focus for an already-labelled control."],
      avoid: ["Essential information (tooltips are not reliably reachable on touch)."],
    },
  },
  {
    name: "ConfirmDialog",
    description: "Dialog wired to a confirm/cancel decision; owns its open state.",
    importPath: "@monorepo-boilerplate/ui",
    sourcePath: "src/recipes/confirm-dialog.tsx",
    examplePath: "examples/confirm-dialog.example.tsx",
    tier: "Recipe",
    renderEnvironment: "client",
    props: [
      {
        name: "trigger",
        type: "ReactNode",
        required: true,
        description: "Control that opens it.",
      },
      {
        name: "title",
        type: "ReactNode",
        required: true,
      },
      {
        name: "description",
        type: "ReactNode",
        required: false,
      },
      {
        name: "confirmLabel",
        type: "string",
        required: false,
        default: '"Confirm"',
      },
      {
        name: "cancelLabel",
        type: "string",
        required: false,
        default: '"Cancel"',
      },
      {
        name: "destructive",
        type: "boolean",
        required: false,
        default: "false",
      },
      {
        name: "onConfirm",
        type: "() => void | Promise<void>",
        required: true,
      },
    ],
    examples: [
      {
        label: "destructive",
        code: '<ConfirmDialog\n  trigger={<Button variant="destructive">Delete</Button>}\n  title="Delete project?"\n  description="This cannot be undone."\n  destructive\n  onConfirm={() => deleteProject(id)}\n/>',
      },
    ],
    intent: {
      use: [
        "Guarding a destructive or irreversible action behind an explicit confirm step.",
        "Keeping the client boundary in one leaf so server parents pass slot props only.",
      ],
      avoid: ["Non-blocking notices — use a toast. Multi-step flows — compose Dialog directly."],
    },
  },
  {
    name: "FormField",
    description: "Labelled Input with optional description and error, accessibly wired.",
    importPath: "@monorepo-boilerplate/ui",
    sourcePath: "src/recipes/form-field.tsx",
    examplePath: "examples/form-field.example.tsx",
    tier: "Recipe",
    renderEnvironment: "server",
    props: [
      {
        name: "id",
        type: "string",
        required: true,
        description: "Ties label, input, and messages.",
      },
      {
        name: "label",
        type: "ReactNode",
        required: true,
      },
      {
        name: "description",
        type: "ReactNode",
        required: false,
      },
      {
        name: "error",
        type: "ReactNode",
        required: false,
        description: "Sets aria-invalid.",
      },
      {
        name: "...input",
        type: 'Omit<ComponentPropsWithRef<"input">, "id">',
        required: false,
      },
    ],
    examples: [
      {
        label: "with error",
        code: '<FormField\n  id="email"\n  label="Email"\n  type="email"\n  description="We never share it."\n  error="Enter a valid email."\n/>',
      },
    ],
    intent: {
      use: [
        "Composing accessible form rows: label + input + helper/error in one unit.",
        "Server-rendered forms — it needs no client hooks (pass an explicit id).",
      ],
      avoid: ["Non-text controls — compose Select/Checkbox with their own label instead."],
    },
  },
  {
    name: "Cta",
    description: "Closing call-to-action panel on an elevated surface with an action slot.",
    importPath: "@monorepo-boilerplate/ui",
    sourcePath: "src/blocks/cta.tsx",
    examplePath: "examples/cta.example.tsx",
    tier: "Block",
    renderEnvironment: "server",
    props: [
      {
        name: "title",
        type: "ReactNode",
        required: true,
      },
      {
        name: "description",
        type: "ReactNode",
        required: false,
      },
      {
        name: "actions",
        type: "ReactNode",
        required: false,
        description: "Action controls slot.",
      },
      {
        name: "className",
        type: "string",
        required: false,
      },
    ],
    examples: [
      {
        label: "default",
        code: '<Cta\n  title="Ready to build?"\n  description="Fork the template and start shipping."\n  actions={<Button>Use this template</Button>}\n/>',
      },
    ],
    intent: {
      use: ["Driving a single conversion near the end of a page (sign up, contact, start)."],
      avoid: ["Competing CTAs — keep one primary action so the choice stays clear."],
    },
  },
  {
    name: "FeatureGrid",
    description: "Responsive grid of feature cards driven by a features list.",
    importPath: "@monorepo-boilerplate/ui",
    sourcePath: "src/blocks/feature-grid.tsx",
    examplePath: "examples/feature-grid.example.tsx",
    tier: "Block",
    renderEnvironment: "server",
    props: [
      {
        name: "features",
        type: "ReadonlyArray<{ title: string; description: string; icon?: ReactNode }>",
        required: true,
      },
      {
        name: "columns",
        type: "2 | 3 | 4",
        required: false,
        default: "3",
      },
      {
        name: "className",
        type: "string",
        required: false,
      },
    ],
    examples: [
      {
        label: "three up",
        code: '<FeatureGrid\n  features={[\n    { title: "Fast", description: "Turbopack dev server." },\n    { title: "Typed", description: "Strict TypeScript everywhere." },\n    { title: "Tested", description: "Vitest and Playwright wired in." },\n  ]}\n/>',
      },
    ],
    intent: {
      use: ["Summarizing 2–8 product capabilities in a scannable, responsive grid."],
      avoid: ["Long comparison tables or data — use a table; keep features brief."],
    },
  },
  {
    name: "Hero",
    description: "Centered page-intro section with title, copy, and action/media slots.",
    importPath: "@monorepo-boilerplate/ui",
    sourcePath: "src/blocks/hero.tsx",
    examplePath: "examples/hero.example.tsx",
    tier: "Block",
    renderEnvironment: "server",
    props: [
      {
        name: "title",
        type: "ReactNode",
        required: true,
      },
      {
        name: "description",
        type: "ReactNode",
        required: false,
      },
      {
        name: "actions",
        type: "ReactNode",
        required: false,
        description: "CTA controls slot.",
      },
      {
        name: "media",
        type: "ReactNode",
        required: false,
        description: "Supporting visual slot.",
      },
      {
        name: "className",
        type: "string",
        required: false,
      },
    ],
    examples: [
      {
        label: "with actions",
        code: '<Hero\n  title="Ship faster"\n  description="An opinionated monorepo starter."\n  actions={<Button>Get started</Button>}\n/>',
      },
    ],
    intent: {
      use: ["Opening a landing or marketing page with a single, clear value proposition."],
      avoid: ["Dense dashboards or app shells — a Hero is for marketing-style intros."],
    },
  },
];
