// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
import { Avatar, Flex } from '@monorepo-boilerplate/ui';
import type { Meta, StoryObj } from '@storybook/react-vite';

const meta = {
  title: 'Data Display/Avatar',
  component: Avatar,
  args: { fallback: 'A' },
  argTypes: {
    variant: { control: { type: 'select' }, options: ['solid', 'soft'] },
    size: { control: { type: 'select' }, options: ['1', '2', '3', '4', '5'] },
    color: { control: { type: 'select' }, options: ['indigo', 'crimson', 'grass', 'amber'] },
  },
  render: (args) => <Avatar {...args} />,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof Avatar>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};

export const Variant: Story = {
  render: () => (
    <Flex gap="3" align="center" wrap="wrap">
      {(['solid', 'soft'] as const).map((value) => (
        <Avatar fallback="A" key={value} variant={value} />
      ))}
    </Flex>
  ),
};

export const Size: Story = {
  render: () => (
    <Flex gap="3" align="center" wrap="wrap">
      {(['1', '2', '3', '4', '5'] as const).map((value) => (
        <Avatar fallback="A" key={value} size={value} />
      ))}
    </Flex>
  ),
};

export const Color: Story = {
  render: () => (
    <Flex gap="3" align="center" wrap="wrap">
      {(['indigo', 'crimson', 'grass', 'amber'] as const).map((value) => (
        <Avatar fallback="A" key={value} color={value} />
      ))}
    </Flex>
  ),
};
