// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
/**
 * User/image avatar with a fallback. variant × size × color.
 *
 * Radix Themes component — re-exported from `@radix-ui/themes`.
 */
export { Avatar, type AvatarProps } from "@radix-ui/themes";
