// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
import { Badge, Flex } from '@monorepo-boilerplate/ui';
import type { Meta, StoryObj } from '@storybook/react-vite';

const meta = {
  title: 'Data Display/Badge',
  component: Badge,
  args: { children: 'Badge' },
  argTypes: {
    variant: { control: { type: 'select' }, options: ['solid', 'soft', 'surface', 'outline'] },
    size: { control: { type: 'select' }, options: ['1', '2', '3'] },
    color: { control: { type: 'select' }, options: ['indigo', 'crimson', 'grass', 'amber'] },
  },
  render: (args) => <Badge {...args} />,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof Badge>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};

export const Variant: Story = {
  render: () => (
    <Flex gap="3" align="center" wrap="wrap">
      {(['solid', 'soft', 'surface', 'outline'] as const).map((value) => (
        <Badge key={value} variant={value}>
          Badge
        </Badge>
      ))}
    </Flex>
  ),
};

export const Size: Story = {
  render: () => (
    <Flex gap="3" align="center" wrap="wrap">
      {(['1', '2', '3'] as const).map((value) => (
        <Badge key={value} size={value}>
          Badge
        </Badge>
      ))}
    </Flex>
  ),
};

export const Color: Story = {
  render: () => (
    <Flex gap="3" align="center" wrap="wrap">
      {(['indigo', 'crimson', 'grass', 'amber'] as const).map((value) => (
        <Badge key={value} color={value}>
          Badge
        </Badge>
      ))}
    </Flex>
  ),
};
