// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
/**
 * Highlighted informational message. Compose Callout.Root/Icon/Text.
 *
 * Radix Themes component — re-exported from `@radix-ui/themes`. Compound parts: Root, Icon, Text.
 */
export { Callout } from '@radix-ui/themes';
