// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
/**
 * Elevated surface container. variant × size.
 *
 * Radix Themes component — re-exported from `@radix-ui/themes`.
 */
export { Card, type CardProps } from '@radix-ui/themes';
