// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
import { Card, Flex } from '@monorepo-boilerplate/ui';
import type { Meta, StoryObj } from '@storybook/react-vite';

const meta = {
  title: 'Data Display/Card',
  component: Card,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof Card>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {
  render: () => <Card>Card</Card>,
};

export const Variant: Story = {
  render: () => (
    <Flex gap="3" align="center" wrap="wrap">
      {(['surface', 'classic', 'ghost'] as const).map((value) => (
        <Card key={value} variant={value}>
          Card
        </Card>
      ))}
    </Flex>
  ),
};

export const Size: Story = {
  render: () => (
    <Flex gap="3" align="center" wrap="wrap">
      {(['1', '2', '3'] as const).map((value) => (
        <Card key={value} size={value}>
          Card
        </Card>
      ))}
    </Flex>
  ),
};
