// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
/**
 * Key/value metadata list. Compose DataList.Root/Item/Label/Value.
 *
 * Radix Themes component — re-exported from `@radix-ui/themes`. Compound parts: Root, Item, Label, Value.
 */
export { DataList } from "@radix-ui/themes";
