// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
/**
 * Determinate/indeterminate progress bar. variant × size × color.
 *
 * Radix Themes component — re-exported from `@radix-ui/themes`.
 */
export { Progress, type ProgressProps } from "@radix-ui/themes";
