// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
import { Skeleton } from "@radix-ui/themes";
import type { Meta, StoryObj } from "@storybook/react-vite";

const meta = {
  title: "Data Display/Skeleton",
  component: Skeleton,
  parameters: { layout: "padded" },
} satisfies Meta<typeof Skeleton>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {
  render: () => <Skeleton>Loading placeholder</Skeleton>,
};
