// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
/**
 * Shimmer placeholder while content loads; wraps its children to match their size.
 *
 * Radix Themes component — re-exported from `@radix-ui/themes`.
 */
export { Skeleton, type SkeletonProps } from '@radix-ui/themes';
