// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
/**
 * Indeterminate loading spinner.
 *
 * Radix Themes component — re-exported from `@radix-ui/themes`.
 */
export { Spinner, type SpinnerProps } from "@radix-ui/themes";
