// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
/**
 * Data table. Compose Table.Root/Header/Body/Row/Cell.
 *
 * Radix Themes component — re-exported from `@radix-ui/themes`. Compound parts: Root, Header, Body, Row, ColumnHeaderCell, RowHeaderCell, Cell.
 */
export { Table } from "@radix-ui/themes";
