import type { ComponentSpec } from "@monorepo-boilerplate/ui/components/components.manifest";

export const BANNER =
  "// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.\n" +
  "// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.\n";

const radixOf = (spec: ComponentSpec): string => spec.radixName ?? spec.name;
const categorySlug = (spec: ComponentSpec): string =>
  spec.category.toLowerCase().replaceAll(" ", "-");
/** Path of a component's generated files, relative to src/components (no extension). */
const relPath = (spec: ComponentSpec): string => `${categorySlug(spec)}/${spec.name}`;

function capitalize(value: string): string {
  return value.charAt(0).toUpperCase() + value.slice(1);
}

/** A single rendered instance: `<Name sampleProps prop={value}>sample</Name>` or self-closing. */
function instance(spec: ComponentSpec, attrs: string): string {
  const rn = radixOf(spec);
  const allAttrs = [spec.sampleProps, attrs].filter(Boolean).join(" ");
  const open = allAttrs ? `${rn} ${allAttrs}` : rn;
  return spec.sample === undefined ? `<${open} />` : `<${open}>${spec.sample}</${rn}>`;
}

/** Generated re-export module for one component. */
export function renderModule(spec: ComponentSpec): string {
  const rn = radixOf(spec);
  const valueClause = rn === spec.name ? rn : `${rn} as ${spec.name}`;

  const clauses = [valueClause];
  // Compound components (namespace objects) don't export a single props type; simple ones do.
  const wantsType =
    spec.propsType !== false && (!spec.compound || typeof spec.propsType === "string");
  if (wantsType) {
    const typeName = spec.propsType ?? `${rn}Props`;
    clauses.push(
      typeName === `${spec.name}Props`
        ? `type ${typeName}`
        : `type ${typeName} as ${spec.name}Props`,
    );
  }

  const parts = spec.parts ? ` Compound parts: ${spec.parts.join(", ")}.` : "";
  const doc = `/**\n * ${spec.usage}\n *\n * Radix Themes component — re-exported from \`@radix-ui/themes\`.${parts}\n */\n`;
  return `${BANNER}${doc}export { ${clauses.join(", ")} } from "@radix-ui/themes";\n`;
}

/** Generated reference story for one component: a Default plus one matrix per declared axis. */
export function renderStory(spec: ComponentSpec): string {
  const rn = radixOf(spec);
  const hasAxes = (spec.axes ?? []).length > 0;
  // `Flex` lays out the matrix rows — only imported when there are axes; dedupe when
  // the component under test IS Flex.
  const named = [...new Set(hasAxes ? [rn, "Flex"] : [rn])].join(", ");
  const imports = `import { ${named} } from "@radix-ui/themes";\nimport type { Meta, StoryObj } from "@storybook/react-vite";\n`;

  const argsLine = spec.metaArgs ? `  args: ${spec.metaArgs},\n` : "";
  const head = `const meta = {\n  title: "${spec.category}/${spec.name}",\n  component: ${rn},\n${argsLine}  parameters: { layout: "padded" },\n} satisfies Meta<typeof ${rn}>;\n\nexport default meta;\n\ntype Story = StoryObj<typeof meta>;\n`;

  const defaultStory = `export const Default: Story = {\n  render: () => ${instance(spec, "")},\n};\n`;

  const axisStories = (spec.axes ?? []).map((axis) => {
    const storyName = capitalize(axis.prop);
    const values = JSON.stringify(axis.values);
    const cell = instance(spec, `key={value} ${axis.prop}={value}`);
    return (
      `export const ${storyName}: Story = {\n` +
      `  render: () => (\n` +
      `    <Flex gap="3" align="center" wrap="wrap">\n` +
      `      {(${values} as const).map((value) => ${cell})}\n` +
      `    </Flex>\n` +
      `  ),\n};\n`
    );
  });

  return [BANNER + imports, head, defaultStory, ...axisStories].join("\n");
}

/** Generated barrel re-exporting every component module (by category path). */
export function renderBarrel(specs: readonly ComponentSpec[]): string {
  const lines = [...specs]
    .toSorted((a, b) => a.name.localeCompare(b.name))
    .map((spec) => `export * from "./${relPath(spec)}";`)
    .join("\n");
  return `${BANNER}\n${lines}\n`;
}

/** Map of generated file path (relative to src/components) → contents for the whole layer. */
export function renderAll(specs: readonly ComponentSpec[]): Record<string, string> {
  const files: Record<string, string> = { "index.ts": renderBarrel(specs) };
  for (const spec of specs) {
    files[`${relPath(spec)}.tsx`] = renderModule(spec);
    // Compound components (and a few single ones like Tooltip) get a hand-authored story —
    // can't be rendered generically; the CLI's banner-safe prune keeps it.
    if (!spec.compound && !spec.manualStory)
      files[`${relPath(spec)}.stories.tsx`] = renderStory(spec);
  }
  return files;
}
