import { existsSync, readdirSync, statSync } from "node:fs";
import { join, relative, resolve } from "node:path";
import { pathToFileURL } from "node:url";

import type { CatalogSidecar, ComponentMeta } from "@monorepo-boilerplate/ui/catalog-schema";
import { COMPONENT_TIERS, toSlug } from "@monorepo-boilerplate/ui/catalog-schema";
import { Project } from "ts-morph";

import { extractVariants, inferRenderEnvironment } from "./infer";

const UI_ROOT = resolve("packages/ui");
const IMPORT_PATH = "@monorepo-boilerplate/ui";
// Sort by the canonical tier order from the schema — no separate list to drift.
const TIER_ORDER: readonly string[] = COMPONENT_TIERS;
const SKIP_DIRS = new Set(["node_modules", "dist"]);

function findSidecars(dir: string): string[] {
  const out: string[] = [];
  let names: string[];
  try {
    names = readdirSync(dir);
  } catch {
    return out;
  }
  for (const name of names) {
    const full = join(dir, name);
    let isDirectory = false;
    try {
      isDirectory = statSync(full).isDirectory();
    } catch {
      continue;
    }
    if (isDirectory) {
      if (!SKIP_DIRS.has(name)) out.push(...findSidecars(full));
    } else if (name.endsWith(".catalog.ts")) {
      out.push(full);
    }
  }
  return out.toSorted();
}

/** Read every `*.catalog.ts` sidecar, infer source-derived fields, and merge. */
export async function buildRegistry(): Promise<ComponentMeta[]> {
  const sidecarPaths = findSidecars(join(UI_ROOT, "src"));
  const project = new Project({ skipAddingFilesFromTsConfig: true });

  const metas = await Promise.all(
    sidecarPaths.map(async (sidecarPath): Promise<ComponentMeta> => {
      const imported = (await import(pathToFileURL(sidecarPath).href)) as { meta?: CatalogSidecar };
      const sidecar = imported.meta;
      if (!sidecar) throw new Error(`${sidecarPath}: missing exported \`meta\``);

      const componentPath = sidecarPath.replace(/\.catalog\.ts$/, ".tsx");
      if (!existsSync(componentPath)) {
        throw new Error(
          `${sidecarPath}: no component file \`${relative(UI_ROOT, componentPath)}\` next to the sidecar`,
        );
      }
      const sourceFile = project.addSourceFileAtPath(componentPath);
      const variants = extractVariants(sourceFile);

      // Enforce "no example ⇒ not in catalog": every component must ship a live
      // `examples/<slug>.example.tsx` ground truth, or generation fails (so
      // `catalog:check` fails in CI).
      const examplePath = join("examples", `${toSlug(sidecar.name)}.example.tsx`);
      if (!existsSync(join(UI_ROOT, examplePath))) {
        throw new Error(
          `${sidecar.name}: missing example file \`${examplePath}\` (every catalogued component needs one)`,
        );
      }

      // Optional fields are set to `undefined` when absent; JSON.stringify drops
      // them, so the generated module stays clean.
      return {
        name: sidecar.name,
        description: sidecar.description,
        importPath: IMPORT_PATH,
        sourcePath: relative(UI_ROOT, componentPath),
        examplePath,
        tier: sidecar.tier,
        // Sidecar may override the inferred environment (e.g. declare "universal").
        renderEnvironment: sidecar.renderEnvironment ?? inferRenderEnvironment(sourceFile),
        props: sidecar.props,
        variants: variants.length > 0 ? variants : undefined,
        examples: sidecar.examples,
        intent: sidecar.intent,
      };
    }),
  );

  return metas.toSorted(
    (a, b) =>
      TIER_ORDER.indexOf(a.tier) - TIER_ORDER.indexOf(b.tier) || a.name.localeCompare(b.name),
  );
}

/** Render the generated registry module source. */
export function renderModule(metas: readonly ComponentMeta[]): string {
  const banner =
    "// Code generated by @monorepo-boilerplate/catalog-extractor. DO NOT EDIT.\n" +
    "// Run `pnpm catalog:generate` to refresh after changing a component or its *.catalog.ts.\n";
  const body = `import type { ComponentMeta } from "./catalog-schema";\n\nexport const componentRegistry: readonly ComponentMeta[] = ${JSON.stringify(metas, null, 2)};\n`;
  return `${banner}\n${body}`;
}
