// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
/**
 * Action trigger. variant × size × color; supports asChild for links.
 *
 * Radix Themes component — re-exported from `@radix-ui/themes`.
 */
export { Button, type ButtonProps } from "@radix-ui/themes";
