// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
import { Button, Flex } from '@monorepo-boilerplate/ui';
import type { Meta, StoryObj } from '@storybook/react-vite';

const meta = {
  title: 'Forms/Button',
  component: Button,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof Button>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {
  render: () => <Button>Button</Button>,
};

export const Variant: Story = {
  render: () => (
    <Flex gap="3" align="center" wrap="wrap">
      {(['classic', 'solid', 'soft', 'surface', 'outline', 'ghost'] as const).map((value) => (
        <Button key={value} variant={value}>
          Button
        </Button>
      ))}
    </Flex>
  ),
};

export const Size: Story = {
  render: () => (
    <Flex gap="3" align="center" wrap="wrap">
      {(['1', '2', '3', '4'] as const).map((value) => (
        <Button key={value} size={value}>
          Button
        </Button>
      ))}
    </Flex>
  ),
};

export const Color: Story = {
  render: () => (
    <Flex gap="3" align="center" wrap="wrap">
      {(['indigo', 'crimson', 'grass', 'amber'] as const).map((value) => (
        <Button key={value} color={value}>
          Button
        </Button>
      ))}
    </Flex>
  ),
};
