// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
import { Checkbox, Flex } from '@monorepo-boilerplate/ui';
import type { Meta, StoryObj } from '@storybook/react-vite';

const meta = {
  title: 'Forms/Checkbox',
  component: Checkbox,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof Checkbox>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {
  render: () => <Checkbox defaultChecked />,
};

export const Variant: Story = {
  render: () => (
    <Flex gap="3" align="center" wrap="wrap">
      {(['classic', 'surface', 'soft'] as const).map((value) => (
        <Checkbox defaultChecked key={value} variant={value} />
      ))}
    </Flex>
  ),
};

export const Size: Story = {
  render: () => (
    <Flex gap="3" align="center" wrap="wrap">
      {(['1', '2', '3'] as const).map((value) => (
        <Checkbox defaultChecked key={value} size={value} />
      ))}
    </Flex>
  ),
};
