// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
/**
 * Square button for a single icon. variant × size × color.
 *
 * Radix Themes component — re-exported from `@radix-ui/themes`.
 */
export { IconButton, type IconButtonProps } from "@radix-ui/themes";
