// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
import { IconButton, Flex } from "@monorepo-boilerplate/ui";
import type { Meta, StoryObj } from "@storybook/react-vite";

const meta = {
  title: "Forms/IconButton",
  component: IconButton,
  parameters: { layout: "padded" },
} satisfies Meta<typeof IconButton>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {
  render: () => <IconButton>+</IconButton>,
};

export const Variant: Story = {
  render: () => (
    <Flex gap="3" align="center" wrap="wrap">
      {(["classic", "solid", "soft", "surface", "outline", "ghost"] as const).map((value) => (
        <IconButton key={value} variant={value}>
          +
        </IconButton>
      ))}
    </Flex>
  ),
};

export const Size: Story = {
  render: () => (
    <Flex gap="3" align="center" wrap="wrap">
      {(["1", "2", "3", "4"] as const).map((value) => (
        <IconButton key={value} size={value}>
          +
        </IconButton>
      ))}
    </Flex>
  ),
};

export const Color: Story = {
  render: () => (
    <Flex gap="3" align="center" wrap="wrap">
      {(["indigo", "crimson", "grass", "amber"] as const).map((value) => (
        <IconButton key={value} color={value}>
          +
        </IconButton>
      ))}
    </Flex>
  ),
};
