// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
/**
 * Selectable radio cards. Compose RadioCards.Root/Item.
 *
 * Radix Themes component — re-exported from `@radix-ui/themes`. Compound parts: Root, Item.
 */
export { RadioCards } from "@radix-ui/themes";
