// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
/**
 * A standalone radio input (usually used via RadioGroup). variant × size.
 *
 * Radix Themes component — re-exported from `@radix-ui/themes`.
 */
export { Radio, type RadioProps } from "@radix-ui/themes";
