// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
/**
 * Single-select segmented toggle. Compose SegmentedControl.Root/Item.
 *
 * Radix Themes component — re-exported from `@radix-ui/themes`. Compound parts: Root, Item.
 */
export { SegmentedControl } from '@radix-ui/themes';
