// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
/**
 * Dropdown single-select. Compose Select.Root/Trigger/Content/Item.
 *
 * Radix Themes component — re-exported from `@radix-ui/themes`. Compound parts: Root, Trigger, Content, Item, Group, Label, Separator.
 */
export { Select } from "@radix-ui/themes";
