// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
/**
 * Range slider. variant × size × color.
 *
 * Radix Themes component — re-exported from `@radix-ui/themes`.
 */
export { Slider, type SliderProps } from '@radix-ui/themes';
