// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
/**
 * Boolean on/off toggle. variant × size × color.
 *
 * Radix Themes component — re-exported from `@radix-ui/themes`.
 */
export { Switch, type SwitchProps } from "@radix-ui/themes";
