// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
import { Switch, Flex } from '@monorepo-boilerplate/ui';
import type { Meta, StoryObj } from '@storybook/react-vite';

const meta = {
  title: 'Forms/Switch',
  component: Switch,
  argTypes: {
    variant: { control: { type: 'select' }, options: ['classic', 'surface', 'soft'] },
    size: { control: { type: 'select' }, options: ['1', '2', '3'] },
    color: { control: { type: 'select' }, options: ['indigo', 'crimson', 'grass', 'amber'] },
  },
  render: (args) => <Switch {...args} />,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof Switch>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};

export const Variant: Story = {
  render: () => (
    <Flex gap="3" align="center" wrap="wrap">
      {(['classic', 'surface', 'soft'] as const).map((value) => (
        <Switch key={value} variant={value} />
      ))}
    </Flex>
  ),
};

export const Size: Story = {
  render: () => (
    <Flex gap="3" align="center" wrap="wrap">
      {(['1', '2', '3'] as const).map((value) => (
        <Switch key={value} size={value} />
      ))}
    </Flex>
  ),
};

export const Color: Story = {
  render: () => (
    <Flex gap="3" align="center" wrap="wrap">
      {(['indigo', 'crimson', 'grass', 'amber'] as const).map((value) => (
        <Switch key={value} color={value} />
      ))}
    </Flex>
  ),
};
