// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
/**
 * Single-line text input. Compose TextField.Root with optional TextField.Slot adornments.
 *
 * Radix Themes component — re-exported from `@radix-ui/themes`. Compound parts: Root, Slot.
 */
export { TextField } from '@radix-ui/themes';
