// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
/**
 * Multi-line text input. variant × size.
 *
 * Radix Themes component — re-exported from `@radix-ui/themes`.
 */
export { TextArea, type TextAreaProps } from "@radix-ui/themes";
