// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
/**
 * Button-triggered menu. Compose DropdownMenu.Root/Trigger/Content/Item.
 *
 * Radix Themes component — re-exported from `@radix-ui/themes`. Compound parts: Root, Trigger, Content, Item, Group, Label, CheckboxItem, RadioGroup, RadioItem, Separator, Sub, SubTrigger, SubContent.
 */
export { DropdownMenu } from "@radix-ui/themes";
