// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
/**
 * Navigation tabs backed by links (for routing). Compose TabNav.Root/Link.
 *
 * Radix Themes component — re-exported from `@radix-ui/themes`. Compound parts: Root, Link.
 */
export { TabNav } from '@radix-ui/themes';
