// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
/**
 * Tabbed panels. Compose Tabs.Root/List/Trigger/Content.
 *
 * Radix Themes component — re-exported from `@radix-ui/themes`. Compound parts: Root, List, Trigger, Content.
 */
export { Tabs } from "@radix-ui/themes";
