// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
/**
 * Constrains its child to a fixed width:height ratio.
 *
 * Radix Themes component — re-exported from `@radix-ui/themes`.
 */
export { AspectRatio, type AspectRatioProps } from "@radix-ui/themes";
