// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
/**
 * Generic layout block with Radix spacing/sizing props. Renders a <div>.
 *
 * Radix Themes component — re-exported from `@radix-ui/themes`.
 */
export { Box, type BoxProps } from '@radix-ui/themes';
