// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
import { Box } from "@radix-ui/themes";
import type { Meta, StoryObj } from "@storybook/react-vite";

const meta = {
  title: "Layout/Box",
  component: Box,
  parameters: { layout: "padded" },
} satisfies Meta<typeof Box>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {
  render: () => <Box>Box</Box>,
};
