// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
/**
 * Constrains content to a max-width and centers it. Sizes 1–4.
 *
 * Radix Themes component — re-exported from `@radix-ui/themes`.
 */
export { Container, type ContainerProps } from "@radix-ui/themes";
