// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
/**
 * Flexbox container: direction, align, justify, wrap, gap (responsive).
 *
 * Radix Themes component — re-exported from `@radix-ui/themes`.
 */
export { Flex, type FlexProps } from '@radix-ui/themes';
