// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
/**
 * CSS grid container: columns, rows, flow, gap (responsive).
 *
 * Radix Themes component — re-exported from `@radix-ui/themes`.
 */
export { Grid, type GridProps } from '@radix-ui/themes';
