// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
import { Grid } from "@monorepo-boilerplate/ui";
import type { Meta, StoryObj } from "@storybook/react-vite";

const meta = {
  title: "Layout/Grid",
  component: Grid,
  parameters: { layout: "padded" },
} satisfies Meta<typeof Grid>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {
  render: () => <Grid>Grid</Grid>,
};
