// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
/**
 * Bleeds a child to the edges of a padded parent (e.g. Card), cancelling padding.
 *
 * Radix Themes component — re-exported from `@radix-ui/themes`.
 */
export { Inset, type InsetProps } from '@radix-ui/themes';
