// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
import { Inset } from '@monorepo-boilerplate/ui';
import type { Meta, StoryObj } from '@storybook/react-vite';

const meta = {
  title: 'Layout/Inset',
  component: Inset,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof Inset>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {
  render: () => <Inset>Inset</Inset>,
};
