// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
/**
 * Scrollable region with styled scrollbars. Constrain its size to scroll.
 *
 * Radix Themes component — re-exported from `@radix-ui/themes`.
 */
export { ScrollArea, type ScrollAreaProps } from "@radix-ui/themes";
