// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
/**
 * Vertical page band with size-based vertical padding (1–4).
 *
 * Radix Themes component — re-exported from `@radix-ui/themes`.
 */
export { Section, type SectionProps } from "@radix-ui/themes";
