// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
/**
 * Thin divider between content; horizontal or vertical, sized and colorable.
 *
 * Radix Themes component — re-exported from `@radix-ui/themes`.
 */
export { Separator, type SeparatorProps } from "@radix-ui/themes";
