// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
/**
 * Hides content visually while keeping it available to screen readers (e.g. labels for icon-only controls, hidden dialog titles).
 *
 * Radix Themes component — re-exported from `@radix-ui/themes`.
 */
export { VisuallyHidden, type VisuallyHiddenProps } from '@radix-ui/themes';
