// Code generated by @monorepo-boilerplate/catalog-codegen. DO NOT EDIT.
// Edit packages/ui/src/components/components.manifest.ts and run `pnpm ui:codegen`.
import { VisuallyHidden } from '@monorepo-boilerplate/ui';
import type { Meta, StoryObj } from '@storybook/react-vite';

const meta = {
  title: 'Layout/VisuallyHidden',
  component: VisuallyHidden,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof VisuallyHidden>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {
  render: () => <VisuallyHidden>Screen-reader-only text</VisuallyHidden>,
};
